# Generated by Django 4.0.6 on 2022-07-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('preamble', models.CharField(max_length=1024, verbose_name='Преамбула')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='Способ разметки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалён')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-created'],
            },
        ),
    ]
